
version: "3.9"

services:
  prodapp:
    environment: 
      - production
    build:
      dockerfile: Dockerfile.prod
      context: .
    volumes:
      - /node_modules
      - .:.
    stdin_open: true
    container_name: prodapp
    restart: always
    ports:
      - "80:3000"    